/*
 * Copyright (C) 2023 Dynamia Soluciones IT S.A.S - NIT 900302344-1
 * Colombia / South America
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package tools.dynamia.contract;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition;
import tools.dynamia.actions.ActionFlowStep;
import tools.dynamia.actions.ActionFlowStepType;
import tools.dynamia.actions.ActionRuntime;
import tools.dynamia.ui.UIPort;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.jar.JarFile;
import java.util.stream.Collectors;

/**
 * Generates the TypeScript types of the Dynamia UI protocol from the Java classes, which are the source of truth: the flow
 * step types, the shape of a step, the runtimes of an action and the catalog of UI ports declared with {@link UIPort}.
 * The output goes to {@code platform/packages/sdk/src/generated/ui-contract.ts}; {@code GeneratedContractTest} fails when
 * the committed file is stale.
 */
public final class ContractGenerator {

    /** Properties of a step that are always present. The rest are optional because the JSON omits nulls. */
    private static final Set<String> REQUIRED = Set.of("flowId", "type");

    private ContractGenerator() {
    }

    /**
     * @return the content of {@code ui-contract.ts}
     */
    public static String generate() {
        var out = new StringBuilder();
        out.append("""
                // GENERATED by platform/contract/ui-contract-generator from the Java sources. DO NOT EDIT.
                // Regenerate with: mvn -pl platform/contract/ui-contract-generator test -Dcontract.update=true

                """);

        out.append("/** Mirrors `tools.dynamia.actions.ActionFlowStepType`. */\n");
        out.append("export const ACTION_FLOW_STEP_TYPES = ").append(array(Arrays.stream(ActionFlowStepType.values()).map(Enum::name).toList())).append(" as const;\n");
        out.append("export type ActionFlowStepType = (typeof ACTION_FLOW_STEP_TYPES)[number];\n\n");

        out.append("/** Mirrors `tools.dynamia.actions.ActionRuntime`: where and how a published action runs. */\n");
        out.append("export const ACTION_RUNTIMES = ").append(array(Arrays.stream(ActionRuntime.values()).map(Enum::name).toList())).append(" as const;\n");
        out.append("export type ActionRuntime = (typeof ACTION_RUNTIMES)[number];\n\n");

        var properties = stepProperties();
        out.append("/** The JSON properties of a step, as `tools.dynamia.actions.ActionFlowStep` serialises them. */\n");
        out.append("export const ACTION_FLOW_STEP_FIELDS = ").append(array(properties.stream().map(BeanPropertyDefinition::getName).toList())).append(" as const;\n\n");

        out.append("/**\n * A single step of a `FlowRemoteAction` flow, mirroring `tools.dynamia.actions.ActionFlowStep`. `data` depends on\n"
                + " * `type`; see the Javadoc of `ActionFlowStepType`.\n */\n");
        out.append("export interface ActionFlowStep {\n");
        for (var property : properties) {
            out.append("    ").append(property.getName()).append(REQUIRED.contains(property.getName()) ? "" : "?").append(": ")
                    .append(tsType(property.getPrimaryType())).append(";\n");
        }
        out.append("}\n\n");

        out.append("/**\n * The UI ports declared with `@UIPort` in Java: the facades an action can use, and the flow steps each one produces\n"
                + " * for a remote client.\n */\n");
        out.append("export const UI_PORTS = {\n");
        for (var port : ports()) {
            var annotation = port.getAnnotation(UIPort.class);
            out.append("    ").append(annotation.name()).append(": { spi: '").append(port.getSimpleName()).append("', steps: ")
                    .append(array(Arrays.asList(annotation.steps()))).append(" },\n");
        }
        out.append("} as const;\n");
        out.append("export type UIPortName = keyof typeof UI_PORTS;\n");
        return out.toString();
    }

    private static List<BeanPropertyDefinition> stepProperties() {
        var mapper = new ObjectMapper();
        var description = mapper.getSerializationConfig().introspect(mapper.constructType(ActionFlowStep.class));
        return description.findProperties().stream()
                .filter(BeanPropertyDefinition::couldSerialize)
                .sorted(Comparator.comparingInt((BeanPropertyDefinition p) -> order(p.getName())))
                .toList();
    }

    /** Keeps the order of the fields stable and readable: identity first, the answer and the token last. */
    private static int order(String name) {
        var order = List.of("flowId", "type", "title", "message", "messageType", "viewDescriptor", "viewClass", "data", "fieldErrors", "hints", "resumeToken");
        int index = order.indexOf(name);
        return index < 0 ? order.size() : index;
    }

    private static String tsType(JavaType type) {
        Class<?> raw = type.getRawClass();
        if (raw == String.class || raw.isEnum() && raw != ActionFlowStepType.class) {
            return "string";
        }
        if (raw == ActionFlowStepType.class) {
            return "ActionFlowStepType";
        }
        if (raw == boolean.class || raw == Boolean.class) {
            return "boolean";
        }
        if (Number.class.isAssignableFrom(raw) || raw.isPrimitive()) {
            return "number";
        }
        if (Map.class.isAssignableFrom(raw)) {
            var value = type.containedTypeOrUnknown(1);
            return "Record<string, " + (value.getRawClass() == Object.class ? "unknown" : tsType(value)) + ">";
        }
        if (raw == Object.class) {
            return "unknown";
        }
        throw new IllegalStateException("No TypeScript type for " + raw.getName() + ": teach ContractGenerator about it");
    }

    private static String array(List<String> values) {
        return values.stream().map(v -> "'" + v + "'").collect(Collectors.joining(", ", "[", "]"));
    }

    /** The classes annotated with {@link UIPort} in the package of the annotation, sorted by port name. */
    static List<Class<?>> ports() {
        var found = new ArrayList<Class<?>>();
        for (String name : classNamesIn(UIPort.class)) {
            try {
                Class<?> type = Class.forName(name, false, UIPort.class.getClassLoader());
                if (type.isAnnotationPresent(UIPort.class)) {
                    found.add(type);
                }
            } catch (ClassNotFoundException | LinkageError e) {
                // not loadable here: it cannot be a port of this artifact
            }
        }
        found.sort(Comparator.comparing(c -> c.getAnnotation(UIPort.class).name()));
        return found;
    }

    private static List<String> classNamesIn(Class<?> anchor) {
        String packagePath = anchor.getPackageName().replace('.', '/');
        try {
            var location = new File(anchor.getProtectionDomain().getCodeSource().getLocation().toURI());
            var names = new ArrayList<String>();
            if (location.isDirectory()) {
                var directory = new File(location, packagePath);
                for (var file : directory.listFiles((dir, n) -> n.endsWith(".class"))) {
                    names.add(anchor.getPackageName() + "." + file.getName().replace(".class", ""));
                }
            } else {
                try (var jar = new JarFile(location)) {
                    jar.stream().map(e -> e.getName())
                            .filter(n -> n.startsWith(packagePath + "/") && n.endsWith(".class") && n.indexOf('/', packagePath.length() + 1) < 0)
                            .forEach(n -> names.add(n.substring(0, n.length() - ".class".length()).replace('/', '.')));
                }
            }
            return names;
        } catch (URISyntaxException e) {
            throw new IllegalStateException(e);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
