@url = http://localhost:8484/api/app/metadata
### Load Metadata
GET {{url}}

### Load Entities
GET {{url}}/entities

### Load Entity
GET {{url}}/entities/mybookstore.domain.Book


### Load Entity Views
GET {{url}}/entities/mybookstore.domain.Book/views

### Load Entity Views
GET {{url}}/entities/mybookstore.domain.Customer/views

### Load Entity Reference
GET {{url}}/entities/ref/Book/1


### Search Entity Reference
GET {{url}}/entities/ref/Book/search?q=My

### Load Entity  Views with entity references
GET {{url}}/entities/mybookstore.domain.BookLog/views